server:
  port: 8080

spring:
  profiles:
    active: local-mysql
  config:
    use-legacy-processing: true
  application:
    name: toy-project

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

    hibernate:
      ddl-auto: create-drop
token:
  expiration-time: 3600000
  secret-key: zest-key
---
spring:
  profiles: local-h2
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
---
spring:
  profiles: local-mysql
  datasource:
    url: jdbc:mysql://localhost:3307/toy?useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234